service: 
    greeting: Hello from DEFAULT 

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/salva?createDatabaseIfNotExist=true
#    username: root
#    password: ferlis05
#  jpa:
#    hibernate:
#      naming:
#       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
    
server:
  port: 8192

hibernate:
    globally_quoted_identifiers: true
    show_sql: true
jpa:
    hibernate:
        naming:
            physical-startegy:org.hibernate.boot.model.naming.PhysicalNamingStartegyStandardImpl
spring:
    jpa:
        hibernate:
            ddl-auto: none
            naming: 
                physical-startegy: org.hibernate.boot.model.naming.PhysicalNamingStartegyStandardImpl
        properties:
          hibernate:
            show_sql: true
            format_sql: true
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@host.docker.internal:1521:xe
        username: salva
        password: salva
   
management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org:
      hibernate:
        type: trace
