service: 
    greeting: Hello from DEFAULT 

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/salva?createDatabaseIfNotExist=true
#    username: root
#    password: ferlis05
#  jpa:
#    hibernate:
#      naming:
#       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
    
server:
  port: 8192

#http://localhost:8192/h2-console
spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
    h2:
        console:
            enabled: true
    datasource:
        platform: h2
        url: jdbc:h2:mem:listofstudent
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

jpa:
    hibernate:
        naming:
            physical-startegy:org.hibernate.boot.model.naming.PhysicalNamingStartegyStandardImpl

