service: 
    greeting: Hello from PROFILE DEFAULT 
    
    
server:
  port: 7171

hibernate:
    globally_quoted_identifiers: true
    show_sql: true

spring:
    jpa:
        hibernate:
            ddl-auto: none
            naming: 
                physical-startegy: org.hibernate.boot.model.naming.PhysicalNamingStartegyStandardImpl
        properties:
          hibernate:
            show_sql: true
            format_sql: true
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@host.docker.internal:1521:xe
        username: salva
        password: salva
# Wo ist der Authorization-Server
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8181/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
      
management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org:
      hibernate:
        type: trace

